language: node_js
node_js:
  - "6"
  - "4"
  - "0.10"
sudo: false
before_install:
  - cp default.config.json config.json
after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
